Milestone 4 complete
OlukaDenis/Calculator pull request #5
Opened 2020-06-26 14:55 UTC by OlukaDenis

Added the operate and calculate helper methods

2020-06-28 06:44 UTC, shshamim63 requested changes
## Status :recycle: Required Changes :recycle: 
___
Hi @OlukaDenis :wave: 
You are almost done with the milestone. Just one major thing is blocking me to approve this right now. Let's resolve it.
___
### :spades: Mandatory Changes :spades: 
___
- You have to decide on which point you are pressing the '+/-' button. Based on that you are going to alter the sign. For example, 
`6 + 5 +/- = should output 1` cause here 5 is changing the sign. But you are changing both.  
___
### :clubs: Optional Changes :clubs: 
___
- I have found some repetition in operate.js. Dry code is always better. Check out the comment.
___
#### Please fix the above-mentioned issue and another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-06-28 06:44 UTC, shshamim63 commented on src/logic/operate.js
> +      result = BigJs(numberOne).plus(BigJs(numberTwo)).toString();
```js
BigJs(numberOne).op(BigJs(numberTwo)).toString();
```
Is actually repetitive. So I think you can declare two variables that will contain numberOne and numberTwo.
```js
const firstNumber = BigJs(numberOne);
const secondNumber = BigJs(numberTwo);
```
then you can use them without repetition.

2020-06-28 06:44 UTC, shshamim63 commented on src/logic/calculate.js
> +  }
Both total and next should not change. You should decide on which one you need to alter the sign.

2020-06-29 15:15 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @OlukaDenis kudos for making all changes as requested please merge and move on to the next things, **this is approved** :slightly_smiling_face: 


**RAPHAEL NORIODE**

2020-06-29 17:20 UTC, merged